backend:
name: github
repo: DITT_GITHUB_NAMN/min-wiki
branch: main


media_folder: "images"
public_folder: "/images"


collections:
- name: "posts"
label: "Artiklar"
folder: "posts"
create: true
slug: "{{slug}}"
fields:
- { label: "Titel", name: "title", widget: "string" }
- { label: "Inneh√•ll", name: "body", widget: "markdown" }
